filter:
    paths: [src/*]
    excluded_paths: [tests/*]
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
